### PR TITLE
Ship a StandaloneExtensionManager for Zend\Feed\Reader

### LINKED ISSUE #6419: missing dependency for zendframework/zend-feed stand-alone
When I use _zendframework/zend-feed_ standalone;

```
{
    "zendframework/zend-feed": "~2.3"
}
```

I get the following error;

```
PHP Fatal error:  Class 'Zend\ServiceManager\AbstractPluginManager' not found in...
```

Seems there is missing a dependency for the feed component.

### PR DESCRIPTION
**Pull request by weierophinney**
In 2.2 or 2.3, we modified `Zend\Feed` to reduce the number of dependencies, and introduced a separated interface for the extension manager to allow using a non-ServiceManager variant (which allowed reducing dependencies).

This patch completes that work by introducing a `StandaloneExtensionManager` that provides the base capabilities necessary to serve the shipped feed and entry extensions. `Zend\Feed\Reader\Reader::getExtensionManager()` has been modified to lazy-load this class when no other extension manager has been set.

This implementation does NOT support registering custom extensions, as the `ExtensionManagerInterface` does not specify such capabilities. If users want to allow or support custom extensions, they would need to create their own implementation or extend the current implementation.

This patch replaces #7179 and will resolve #6419.

### CODE REVIEW

File: tests/ZendTest/Feed/Reader/StandaloneExtensionManagerTest.php [hunk 1]
```diff
@@ -0,0 +1,70 @@
+<?php
```
Comment (samsonasik) [inline tests/ZendTest/Feed/Reader/StandaloneExtensionManagerTest.php]: missing license here...

File: tests/ZendTest/Feed/Reader/StandaloneExtensionManagerTest.php [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+namespace ZendTest\Feed\Reader;
+
+use PHPUnit_Framework_TestCase as TestCase;
+use Zend\Feed\Reader\StandaloneExtensionManager;
+
+class StandaloneExtensionManagerTest extends TestCase
+{
+    public function setUp()
+    {
+        $this->extensions = new StandaloneExtensionManager();
```
Comment (samsonasik) [inline tests/ZendTest/Feed/Reader/StandaloneExtensionManagerTest.php]: need <code>protected $extensions</code> as class property

Comment (weierophinney) [inline tests/ZendTest/Feed/Reader/StandaloneExtensionManagerTest.php]: No, we don't. We often omit the property declarations and just use public properties in the test suite.

File: tests/ZendTest/Feed/Reader/StandaloneExtensionManagerTest.php (hunk 1 above)
Comment (weierophinney) [inline tests/ZendTest/Feed/Reader/StandaloneExtensionManagerTest.php]: Fixed.
